
# parsetab_astmatch.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '8770632605DBD8511D3EC8B9BC5D91A8'
    
_lr_action_items = {'RBK':([3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,],[-9,-13,-7,-8,-13,-5,-10,-12,-6,-11,-3,18,-13,-2,-4,]),'WORD':([6,],[13,]),'CODE':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,7,-9,-13,7,-7,-8,-13,-13,7,-12,-6,7,7,-13,-2,7,]),'OR':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,4,-9,-13,4,-7,-8,-13,-13,4,-12,-6,4,4,-13,-2,4,]),'STAR':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,-13,-9,-13,12,-7,-8,-13,-13,-10,-12,-6,-11,-13,-13,-2,-13,]),'NOT':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,9,-9,-13,9,-7,-8,-13,-13,9,-12,-6,9,9,-13,-2,9,]),'LBK':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,10,-9,-13,10,-7,-8,-13,-13,10,-12,-6,10,10,-13,-2,10,]),'COMMA':([3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,],[-9,-13,-7,-8,-13,-5,-10,-12,-6,-11,-3,17,-13,-2,-4,]),'SPECIAL':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,6,-9,-13,6,-7,-8,-13,-13,6,-12,-6,6,6,-13,-2,6,]),'$end':([0,1,2,3,4,7,8,9,11,12,13,14,18,],[-13,0,-1,-9,-13,-7,-8,-13,-10,-12,-6,-11,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ast_special':([2,5,11,14,15,19,],[8,8,8,8,8,8,]),'ast_set':([2,5,11,14,15,19,],[3,3,3,3,3,3,]),'ast_expr':([0,2,4,5,9,10,11,14,15,17,19,],[2,5,11,5,14,15,5,5,5,19,5,]),'ast_match':([0,],[1,]),'ast_exprlist':([10,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ast_match","S'",1,None,None,None),
  ('ast_match -> ast_expr','ast_match',1,'p_ast_match','js_ast_match.py',46),
  ('ast_set -> LBK ast_exprlist RBK','ast_set',3,'p_ast_set','js_ast_match.py',52),
  ('ast_exprlist -> ast_expr','ast_exprlist',1,'p_ast_exprlist','js_ast_match.py',60),
  ('ast_exprlist -> ast_exprlist COMMA ast_expr','ast_exprlist',3,'p_ast_exprlist','js_ast_match.py',61),
  ('ast_exprlist -> <empty>','ast_exprlist',0,'p_ast_exprlist','js_ast_match.py',62),
  ('ast_special -> SPECIAL WORD','ast_special',2,'p_ast_noderef','js_ast_match.py',76),
  ('ast_expr -> ast_expr CODE','ast_expr',2,'p_ast_expr','js_ast_match.py',82),
  ('ast_expr -> ast_expr ast_special','ast_expr',2,'p_ast_expr','js_ast_match.py',83),
  ('ast_expr -> ast_expr ast_set','ast_expr',2,'p_ast_expr','js_ast_match.py',84),
  ('ast_expr -> ast_expr OR ast_expr','ast_expr',3,'p_ast_expr','js_ast_match.py',85),
  ('ast_expr -> ast_expr NOT ast_expr','ast_expr',3,'p_ast_expr','js_ast_match.py',86),
  ('ast_expr -> ast_expr ast_expr STAR','ast_expr',3,'p_ast_expr','js_ast_match.py',87),
  ('ast_expr -> <empty>','ast_expr',0,'p_ast_expr','js_ast_match.py',88),
]
