
# parsetab_astmatch.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ast_matchLBK RBK WORD OR CODE NOT COMMA SPECIAL STARast_match : ast_expr\n  ast_set : LBK ast_exprlist RBK\n  \n  ast_exprlist : ast_expr\n                  | ast_exprlist COMMA ast_expr\n                  |\n  ast_special : SPECIAL WORD\n  ast_expr : ast_expr CODE\n              | ast_expr ast_special\n              | ast_expr ast_set\n              | ast_expr OR ast_expr\n              | ast_expr NOT ast_expr\n              | ast_expr ast_expr STAR\n              |\n  '
    
_lr_action_items = {'COMMA':([3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,],[-13,-13,-5,-8,-7,-9,-10,-11,-12,-6,-3,18,-2,-13,-4,]),'SPECIAL':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,6,-13,-13,6,-13,-8,-7,-9,6,6,-12,-6,6,-2,-13,6,]),'OR':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,3,-13,-13,3,-13,-8,-7,-9,3,3,-12,-6,3,-2,-13,3,]),'LBK':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,7,-13,-13,7,-13,-8,-7,-9,7,7,-12,-6,7,-2,-13,7,]),'$end':([0,1,2,3,4,8,9,10,11,12,13,14,17,],[-13,0,-1,-13,-13,-8,-7,-9,-10,-11,-12,-6,-2,]),'STAR':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,-13,-13,-13,13,-13,-8,-7,-9,-10,-11,-12,-6,-13,-2,-13,-13,]),'CODE':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,9,-13,-13,9,-13,-8,-7,-9,9,9,-12,-6,9,-2,-13,9,]),'NOT':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,],[-13,4,-13,-13,4,-13,-8,-7,-9,4,4,-12,-6,4,-2,-13,4,]),'RBK':([3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,],[-13,-13,-5,-8,-7,-9,-10,-11,-12,-6,-3,17,-2,-13,-4,]),'WORD':([6,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ast_expr':([0,2,3,4,5,7,11,12,15,18,19,],[2,5,11,12,5,15,5,5,5,19,5,]),'ast_special':([2,5,11,12,15,19,],[8,8,8,8,8,8,]),'ast_set':([2,5,11,12,15,19,],[10,10,10,10,10,10,]),'ast_match':([0,],[1,]),'ast_exprlist':([7,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ast_match","S'",1,None,None,None),
  ('ast_match -> ast_expr','ast_match',1,'p_ast_match','js_ast_match.py',46),
  ('ast_set -> LBK ast_exprlist RBK','ast_set',3,'p_ast_set','js_ast_match.py',52),
  ('ast_exprlist -> ast_expr','ast_exprlist',1,'p_ast_exprlist','js_ast_match.py',60),
  ('ast_exprlist -> ast_exprlist COMMA ast_expr','ast_exprlist',3,'p_ast_exprlist','js_ast_match.py',61),
  ('ast_exprlist -> <empty>','ast_exprlist',0,'p_ast_exprlist','js_ast_match.py',62),
  ('ast_special -> SPECIAL WORD','ast_special',2,'p_ast_noderef','js_ast_match.py',76),
  ('ast_expr -> ast_expr CODE','ast_expr',2,'p_ast_expr','js_ast_match.py',82),
  ('ast_expr -> ast_expr ast_special','ast_expr',2,'p_ast_expr','js_ast_match.py',83),
  ('ast_expr -> ast_expr ast_set','ast_expr',2,'p_ast_expr','js_ast_match.py',84),
  ('ast_expr -> ast_expr OR ast_expr','ast_expr',3,'p_ast_expr','js_ast_match.py',85),
  ('ast_expr -> ast_expr NOT ast_expr','ast_expr',3,'p_ast_expr','js_ast_match.py',86),
  ('ast_expr -> ast_expr ast_expr STAR','ast_expr',3,'p_ast_expr','js_ast_match.py',87),
  ('ast_expr -> <empty>','ast_expr',0,'p_ast_expr','js_ast_match.py',88),
]
