
# parsetab_astmatch.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '8770632605DBD8511D3EC8B9BC5D91A8'
    
_lr_action_items = {'OR':([0,2,3,5,6,7,8,9,10,11,12,13,14,16,17,18,19,],[-13,5,5,-13,-9,-8,-13,-7,-13,-12,-6,5,5,5,-2,-13,5,]),'WORD':([4,],[12,]),'RBK':([5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,],[-13,-9,-8,-5,-7,-13,-12,-6,-10,-3,17,-11,-2,-13,-4,]),'STAR':([0,2,3,5,6,7,8,9,10,11,12,13,14,16,17,18,19,],[-13,-13,11,-13,-9,-8,-13,-7,-13,-12,-6,-10,-13,-11,-2,-13,-13,]),'CODE':([0,2,3,5,6,7,8,9,10,11,12,13,14,16,17,18,19,],[-13,9,9,-13,-9,-8,-13,-7,-13,-12,-6,9,9,9,-2,-13,9,]),'SPECIAL':([0,2,3,5,6,7,8,9,10,11,12,13,14,16,17,18,19,],[-13,4,4,-13,-9,-8,-13,-7,-13,-12,-6,4,4,4,-2,-13,4,]),'LBK':([0,2,3,5,6,7,8,9,10,11,12,13,14,16,17,18,19,],[-13,8,8,-13,-9,-8,-13,-7,-13,-12,-6,8,8,8,-2,-13,8,]),'COMMA':([5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,],[-13,-9,-8,-5,-7,-13,-12,-6,-10,-3,18,-11,-2,-13,-4,]),'$end':([0,1,2,5,6,7,9,10,11,12,13,16,17,],[-13,0,-1,-13,-9,-8,-7,-13,-12,-6,-10,-11,-2,]),'NOT':([0,2,3,5,6,7,8,9,10,11,12,13,14,16,17,18,19,],[-13,10,10,-13,-9,-8,-13,-7,-13,-12,-6,10,10,10,-2,-13,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ast_special':([2,3,13,14,16,19,],[7,7,7,7,7,7,]),'ast_expr':([0,2,3,5,8,10,13,14,16,18,19,],[2,3,3,13,14,16,3,3,3,19,3,]),'ast_exprlist':([8,],[15,]),'ast_match':([0,],[1,]),'ast_set':([2,3,13,14,16,19,],[6,6,6,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ast_match","S'",1,None,None,None),
  ('ast_match -> ast_expr','ast_match',1,'p_ast_match','js_ast_match.py',46),
  ('ast_set -> LBK ast_exprlist RBK','ast_set',3,'p_ast_set','js_ast_match.py',52),
  ('ast_exprlist -> ast_expr','ast_exprlist',1,'p_ast_exprlist','js_ast_match.py',60),
  ('ast_exprlist -> ast_exprlist COMMA ast_expr','ast_exprlist',3,'p_ast_exprlist','js_ast_match.py',61),
  ('ast_exprlist -> <empty>','ast_exprlist',0,'p_ast_exprlist','js_ast_match.py',62),
  ('ast_special -> SPECIAL WORD','ast_special',2,'p_ast_noderef','js_ast_match.py',76),
  ('ast_expr -> ast_expr CODE','ast_expr',2,'p_ast_expr','js_ast_match.py',82),
  ('ast_expr -> ast_expr ast_special','ast_expr',2,'p_ast_expr','js_ast_match.py',83),
  ('ast_expr -> ast_expr ast_set','ast_expr',2,'p_ast_expr','js_ast_match.py',84),
  ('ast_expr -> ast_expr OR ast_expr','ast_expr',3,'p_ast_expr','js_ast_match.py',85),
  ('ast_expr -> ast_expr NOT ast_expr','ast_expr',3,'p_ast_expr','js_ast_match.py',86),
  ('ast_expr -> ast_expr ast_expr STAR','ast_expr',3,'p_ast_expr','js_ast_match.py',87),
  ('ast_expr -> <empty>','ast_expr',0,'p_ast_expr','js_ast_match.py',88),
]
